### ISSUE TITLE
salt_cloud_certs broken by pull #106 ("Don't overwrite salt variable")

### ISSUE THREAD

**Issue by xenophonf** [saltstack-formulas/salt-formula#113]
In context, see https://github.com/saltstack-formulas/salt-formula/commit/cb3aa80c62d448c21f1334c07e02d0c56a87f765#diff-cc4a14e8ec642fa03a6038c172bd52b0L46.

The original Pillar lookup had nothing to do with the salt variable that was renamed to salt_settings.  Instead, it was querying the value of the Pillar key "salt_cloud_certs".  This commit changes the Pillar key to "salt:salt_cloud_certs" without also updating https://github.com/saltstack-formulas/salt-formula/blob/master/salt/files/key and https://github.com/saltstack-formulas/salt-formula/blob/master/pillar.example, and it violates [POLA](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) in that it breaks working salt-cloud configurations managed by salt-formula.

**Comment by iggy** [comment]
Good catch. I'll send a patch to fix it up.

**Comment by xenophonf** [comment]
@iggy, I just filed a pull request that reverts the problematic change:

https://github.com/saltstack-formulas/salt-formula/issues/114

**Comment by iggy** [comment]
Thanks. I hoped to get to it over the weekend, but I got hung up on other stuff (garage doors don't paint themselves :/ )

Looks good to me :+1:

**Comment by gravyboat** [comment]
I'll merge this then.

**Comment by xenophonf** [comment]
Awesome.  Thanks, all!
