### ISSUE TITLE
Update the salt formulas to leverage the new 2014.7.0 features out of the box.

### ISSUE THREAD

**Issue by eedgar** [saltstack-formulas/salt-formula#115]
I am looking to have the state do the steps outlined in this doc out of the box.

apt-get install python-service-identity python-cherrypy
salt-call --local tls.create_self_signed_cert
http://docs.saltstack.com/en/latest/ref/netapi/all/salt.netapi.rest_cherrypy.html

**Comment by iggy** [comment]
You can easily write this into your own states. Fwiw, I wouldn't want the formula automatically creating self-signed certs. That's something a user should have to specifically enable.

**Comment by eedgar** [comment]
I think a flag in the pillar to do it automatically or not would be useful to add.  I see your point, but if people might be doing this then it makes sense in my opinion to make it a little easier for them.

**Comment by gravyboat** [comment]
Woah this is an old issue, if something like this occurs I'd prefer to see it in a separate state.
