### ISSUE TITLE
Alter the formula to support pygit2 on FreeBSD

### ISSUE THREAD

**Issue by xenophonf** [saltstack-formulas/salt-formula#159]
The process of installing from source must be completely overhauled.

A binary package named py27-pygit2 is available on FreeBSD.

**Comment by gravyboat** [comment]
Can this be closed?

**Comment by iggy** [comment]
> I'm not prepared to tackle building pygit2 et al from scratch, so this pull request only partially closes #159.
> -- xenophonf
