### ISSUE TITLE
Reduce amount of configuration in rendered configuration files

### ISSUE THREAD

**Issue by genuss** [saltstack-formulas/salt-formula#162]
For example in this [one](https://github.com/saltstack-formulas/salt-formula/blob/master/salt/files/master.d/f_defaults.conf) we can see many default comments.
Although this is important for new users, the comments make much harder to navigate among all this lines.
Moreover if meaning of some parameter changes and we don't syncronize the change with [original](https://github.com/saltstack/salt/tree/develop/conf), our words will be confusing.

What do you think about removing these comments?

**Comment by puneetk** [comment]
Add a configurable file.replace state that replaces all lines that start with '#' and send over a pull request. Its a good idea.

**Comment by genuss** [comment]
Great, will definitely do that!

**Comment by babilen** [comment]
+1

**Comment by genuss** [comment]
Just started to do that.
If I use file.replace on manage file, than I will always get "changed" result. I suppose it's not good idea at all. Am I missing something?

**Comment by Sjd-Risca** [comment]
Yes, you're right. Maybe the best approach could be to integrate this option into the formula.
From my point of view I prefer to have the comments, both because as a reminder of what an option means, both because it's easier to highlight the diff when I do a package upgrade of saltstack.

**Comment by aboe76** [comment]
@genuss I would like to keep the comments even in the f_defaults.conf file this formula can generate,
Even though it will generate a larger file it will provide information on what each option does.

**Comment by genuss** [comment]
OK, as we don't have a simple solution let's leave things like they are now.
