### ISSUE TITLE
salt.minion fails with syntax error: no test named 'mapping' RHEL6/Jinja 2.2.1

### ISSUE THREAD

**Issue by bradthurber** [saltstack-formulas/salt-formula#170]
It looks like [mapping test requires Jinja2 v2.6 or higher](http://jinja.pocoo.org/docs/dev/templates/#builtin-tests) and I'm on 2.2.1 - which is the best RHEL 6 provides.

```
          ID: salt-minion
    Function: file.recurse
        Name: /etc/salt/minion.d
      Result: False
     Comment: #### /etc/salt/minion.d/f_defaults.conf ####
              Unable to manage file: Jinja syntax error: no test named 'mapping'
              /var/cache/salt/minion/files/base/salt/formulas.jinja(14):
              ---
              [...]

              {%- macro formulas_git_opt(env, opt) -%}
              {%- set value = salt['pillar.get']('salt_formulas:git_opts:{0}:{1}'.format(env, opt),
                   salt['pillar.get']('salt_formulas:git_opts:default:{0}'.format(opt),
                     defaults[opt])) -%}
              {%- if value is mapping -%}    <======================
              {{ value|yaml }}
              {%- else -%}
              {{ value }}
              {%- endif -%}
              {%- endmacro -%}
```

```
# salt-master --versions
           Salt: 2015.5.3
         Python: 2.6.6 (r266:84292, Nov 21 2013, 10:50:32)
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.5.0
           RAET: Not Installed
            ZMQ: 4.0.5
           Mako: 0.3.4
        Tornado: Not Installed
```

**Comment by bradthurber** [comment]
It looks like I'm not the first to run into this: https://github.com/saltstack/salt/issues/11267

Maybe a "This formula requires jinja2 2.6.0 or later" notice could be put at the top of this formula's README.rst file so others don't go down this rabbit hole?

**Comment by puneetk** [comment]
@bradthurber yes, good call, could you send a pull to the readme with that notice. Also i recommend trying to add jinja 2.6 your deployment, not sure what other features are missing.

**Comment by pgporada** [comment]
On centos 6, you can install python-jinja2-26 from the EPEL repo. However, the problem is then figuring out how to make salt use python-jinja2-26 instead of python-jinja2. Does anyone know how to do this?

**Comment by gravyboat** [comment]
@pgporada You'd have to repackage salt and make that the requirement instead of python-jinja2, I highly recommend against that. Can you not simply host the python-jinja2 package internally?

**Comment by pgporada** [comment]
Gravyboat, I'm not exactly sure how to do that. Would that be hosting my own yum repository?

**Comment by gravyboat** [comment]
@pgporada Yep! Or if you wanted you could create a local yum repo: https://wiki.centos.org/HowTos/CreateLocalRepos obviously this isn't as clean or as flexible as a full blown repo, but it's easier to set up.

**Comment by iggy** [comment]
Or we could just take that mapping test out of the formula...

**Comment by gravyboat** [comment]
@iggy I figured people didn't want to do that otherwise they would have just forked and done it themselves.

**Comment by iggy** [comment]
That's what I did. I just never got around to pushing it back upstream.

**Comment by gravyboat** [comment]
https://github.com/saltstack-formulas/salt-formula/pull/173 should fix this one. Please confirm and we'll close this. Thanks @iggy.

**Comment by bradthurber** [comment]
Confirmed salt.minion working now with latest version of formula and Jinja 2.2.1

**Comment by gravyboat** [comment]
Thanks for confirming @bradthurber!

**Comment by keesbos** [comment]
BTW. This is what I did for RedHat 6 etc to update jinja2:
```
su -
cd /tmp
wget https://bitbucket.org/pypa/setuptools/raw/bootstrap/ez_setup.py -O - | python
easy_install -U jinja2
python -c 'import jinja2;print jinja2.__version__'
rm -f setuptools-18.5.zip
```
Note that this changes the use of jinja2 system wide.
