### ISSUE TITLE
Vagrant Example fails with 'Conflicting ID "master" '

### ISSUE THREAD

**Issue by djibi2** [saltstack-formulas/salt-formula#217]
To reproduce:

```
> vagrant up
> vagrant ssh
> sudo salt '*' state.highstate
salt:
    Data failed to compile:
----------
    Pillar failed to render with the following messages:
----------
    Rendering SLS 'salt' failed, render error:
Conflicting ID "master"

```
The same error occurs if any of the other command options listed on the Readme are used: `state.sls salt.(master|minion|cloud)`.

Here is the version report from the vagrant VM:

```
> sudo salt '*' test.versions_report
salt:
               Salt: 0.17.5
             Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
             Jinja2: 2.7.2
           M2Crypto: 0.21.1
     msgpack-python: 0.3.0
       msgpack-pure: Not Installed
           pycrypto: 2.6.1
             PyYAML: 3.10
              PyZMQ: 14.0.1
                ZMQ: 4.0.4


```

**Comment by UtahDave** [comment]
the example pillar has two `master` sections. PR coming soon

**Comment by UtahDave** [comment]
Also, that's a horribly old version of Salt. we should modify this to use the latest from repo.saltstack.com

**Comment by UtahDave** [comment]
Also, this PR causes this formula to use repo.saltstack.com so as to get the latest stable version of Salt.

https://github.com/saltstack-formulas/salt-formula/pull/219
