### ISSUE TITLE
Bad /etc/apt/sources.list.d/saltstack.list generated

### ISSUE THREAD

**Issue by darkpixel** [saltstack-formulas/salt-formula#270]
```
root@uslogdcnas04:~# cat /etc/apt/sources.list.d/saltstack.list 
deb http://repo.saltstack.com/apt/debian/8/amd64/latest Debian 8 GNU/Linux main (jessie)
root@uslogdcnas04:~# 
```

It looks like map.jinja is generating that part by looking at ```salt['grains.get']('oscodename')```.

On that particular machine, the ```oscodename``` grain returns:
```
    oscodename:
        Debian GNU/Linux 8 (jessie)
```

I polled ~100 other machines on my network, and they all return 'jessie', 'wheezy', 'trusty', etc...so I don't think it's a problem with the formula.

After doing a bit more research, it looks like it might be related to this issue: https://github.com/saltstack/salt/issues/30123

I'm going to file a bug against salt and I'll link the two of them shortly.

**Comment by ek9** [comment]
Link for related bug in Salt: https://github.com/saltstack/salt/issues/34423

**Comment by aboe76** [comment]
closing issue, upstream saltstack/salt#34423 is closed
