### ISSUE TITLE
file_roots not updated

### ISSUE THREAD

**Issue by baniobloom** [saltstack-formulas/salt-formula#326]
state/top.sls:
```
base:
  '*':
    - common.*
    - vim
    - vim.salt
  'G@roles:saltmaster':
    - saltmaster.*
    - salt.formulas
```
pillar/top.sls:
```
base:
  '*':
    - common.ssh_keys
  'G@roles:saltmaster':
    - saltmaster.ssh_keys
    - salt_formulas
```
pillar/salt_formula/init.sls:
```
salt_formulas:
  list:
    base:
      - salt-formula
      - vim-formula
```
My understanding from the README is that a file_root should be inserted into /etc/salt/master automatically for each formula like this:
```
file_roots:
  base:
    - /srv/formulas/salt-formula
    - /srv/formulas/vim-formula
```
This isn't happening. So I'm getting the error:
```
[ERROR   ] Template was specified incorrectly: False
[ERROR   ] Template was specified incorrectly: False
local:
    Data failed to compile:
----------
    No matching sls found for 'vim' in env 'base'
----------
    No matching sls found for 'vim.salt' in env 'base'
```

**Comment by aboe76** [comment]
@baniobloom isn't this a chicken and egg problem,
vim will run before the salt-formulas state. so in order to comply you need to have run salt.formulas first
so it will clone the vim-formula in it's place.

**Comment by baniobloom** [comment]
@aboe76 right you are. salt.formulas must be run first.

**Comment by aboe76** [comment]
@baniobloom hope this fixes your problem, please remember, everytime you add a formula to the list the salt.formulas state must run before it can be used.

**Comment by aboe76** [comment]
@baniobloom can we close this issue?

**Comment by baniobloom** [comment]
Yup thanks

**Comment by gentoo9ball** [comment]
@baniobloom, @aboe76  When reading the current documentation, I'm confused. Maybe the documentation should be reworded, "and makes them available in the relevant file_roots settings."

I've gotten the formulas to download into /srv/formulas. However, your initial statement is true, they do not get added to file_roots. After I apply the salt.formulas state, the new folders appear with my specified formulas, but nothing has been added to /etc/salt/master, and I don't believe salt master gets restarted.

I'm sure this isn't my only problem. I've been trying to get aptmirror to work correctly, and even after adding it to /etc/salt/master (file_roots: /srv/formulas/aptmirror-formula), it still doesn't work.

As a noob, just wanted to point out that the documentation is misleading or incomplete at best

**Comment by aboe76** [comment]
@gentoo9ball,I think I can clarify this:

if you use the state ```salt.formulas``` this will only download the specified formulas to ```/srv/formulas```

when running the state ```salt.master``` then the file ```/etc/salt/master.d/f_defaults.conf``` will be updated with the ```file_roots``` and the file /etc/salt/master will be untouched, (by formula design)

So the order is important here:
1. salt.formulas
2. salt.master

**Comment by daks** [comment]
@gentoo9ball I agree with you about the confusing wording in doc. What could be better?

**Comment by gentoo9ball** [comment]
> @gentoo9ball I agree with you about the confusing wording in doc. Any idea for a better one?

"and makes them available in the relevant file_roots settings. REMEMBER to apply this setting with the salt.master state."

?? Something simple

**Comment by droope** [comment]
I was also confused by this, I ended up adding the lines manually to my master configuration. I'll try and create a PR for the documentation.
