### ISSUE TITLE
SLS Rendering Error - 2017.7.0

### ISSUE THREAD

**Issue by ghovat** [saltstack-formulas/salt-formula#329]
Hi,
I have a bug with a salt minion version 2017.7.0 (master has the same version [ there are no problems])
During a state.apply I get from salt-formula a Rendering error:

```
local:
    Data failed to compile:
----------
    Rendering SLS 'base:salt.minion' failed: Jinja variable 'dict object' has no attribute 'iteritems'
/var/cache/salt/minion/files/base/salt/map.jinja(8):
---
[...]

{%- macro deep_merge(a, b) %}
{#-     This whole `'dict' in x.__class__.__name__` mess is a 
        workaround for the missing mapping test in CentOS 6's 
        ancient Jinja2, see #193  #}
{%-     for k,v in b.iteritems() %}    <======================
{%-         if v is string or v is number %}
{%-             do a.update({ k: v }) %}
{%-         elif 'dict' not in v.__class__.__name__ %}
{%-             if a[k] is not defined %}
{%-                 do a.update({ k: v }) %}
[...]
---

```

Salt is on the newest version and also salt-formula is on the latest state.
Do you have a fix for this issue?
Thanks
best
G

**Comment by mechleg** [comment]
Without knowing the versions of OS and other software you are running, I am guessing you are seeing the issue where Python 3.x has removed the dict.iteritems() function.  

IIRC, you can just replace iteritems() with items() and it should work the same.

**Comment by 0xf10e** [comment]
Yeah, that's #296. I'm surprised an instance of `iteritems()` survived for so long as the preparation for python 3 compatibility is going on for at least two years.

**Comment by ghovat** [comment]
@mechleg @0xf10e Yes that was the problem. 
Is there a official fix planned?

**Comment by aboe76** [comment]
@ghovat see pr #330
