### ISSUE TITLE
ldap publisher_acl by hostname

### ISSUE THREAD

**Issue by wesleyarthur** [saltstack-formulas/salt-formula#370]
It doesn't seem like the ldap section of the f_defaults.conf can handle specifying only web* minions like this:

```
publisher_acl:
  fred:
    - web*:
      - test.*
      - pkg.*
```

It ends up generating this and the salt master can't process it. It ends up turning into this wrapped in extra single quotes:

```
publisher_acl:
  fred:
     - '{'web*': ['test.*', 'pkg.*']}'
```

It should look something like this (without the single quotes on the ends):

```
publisher_acl:
  fred:
    - {'web*': ['test.*', 'pkg.*']}
```

**Comment by aboe76** [comment]
fixed with #379
