### ISSUE TITLE
Maintain versioning in FORMULA file

### ISSUE THREAD

**Issue by poliva83** [saltstack-formulas/salt-formula#385]
This repo was forked by someone in my company as some point in time and it is not easy to figure out how many updated to formula has occurred since this time. Would be nice to release official versions of formula and update FORMULA metadata file.

https://github.com/saltstack-formulas/salt-formula/blob/master/FORMULA

**Comment by myii** [comment]
@poliva83 You're absolutely right and this will be resolved when our `semantic-release` solution from the `template-formula` is added to this formula.

**Comment by daks** [comment]
I think this issue can be closed now that semantic release has been implemented

**Comment by myii** [comment]
Thanks, @daks.
