### ISSUE TITLE
salt.formula always runs git.latest and ignores the update setting.

### ISSUE THREAD

**Issue by andrew-vant** [saltstack-formulas/salt-formula#403]
The culprit appears to be commit 2a0f461 in #391, which...checks if the repo is already present by trying to remove it? I can't possibly be understanding that correctly.

**Comment by myii** [comment]
@noelmcloughlin Do we need to revert this change?

**Comment by andrew-vant** [comment]
Reverting it in my local repo does fix the problem, just for the record.

**Comment by myii** [comment]
@andrew-vant Thanks for confirming that.

**Comment by daks** [comment]
Can we add tests to prevent furthur regression?

**Comment by myii** [comment]
Thanks for the report @andrew-vant -- fixed in #413.

**Comment by andrew-vant** [comment]
Thanks, I'll check it out when I have a moment.
