### ISSUE TITLE
[FEATURE] Please support pillarenv_from_saltenv in minion pillar

### ISSUE THREAD

**Issue by windowsrefund** [saltstack-formulas/salt-formula#457]
https://docs.saltstack.com/en/latest/ref/configuration/minion.html#pillarenv-from-saltenv

**Comment by myii** [comment]
@windowsrefund You can already do this using TOFS, you can see this comment here for some background: https://github.com/saltstack-formulas/salt-formula/pull/398#issuecomment-499354351.  The whole discussion explains why the current template will have to be deprecated in the long term.

Essentially, just put any override files under any of the following places:

* `salt/files/{{minion_id}}/minion.d/`
* `salt/files/{{os_family}}/minion.d/`
* `salt/files/default/minion.d/`

**Comment by windowsrefund** [comment]
Thank you very much.
