### ISSUE TITLE
[BUG] pkgrepo uri wrong on ubuntu20

### ISSUE THREAD

**Issue by noelmcloughlin** [saltstack-formulas/salt-formula#483]
### Pillar / config used

---

### Describe the bug

Failed state on Ubuntu 20.04

```
          ID: salt-pkgrepo-install-saltstack-debian
    Function: pkgrepo.managed
        Name: deb http://repo.saltstack.com/apt/ubuntu/20.04/amd64/latest focal main
      Result: False
     Comment: Failed to configure repo 'deb http://repo.saltstack.com/apt/ubuntu/20.04/amd64/latest focal main': Error: HTTP 404: Not Found reading https://repo.saltstack.com/apt/ubuntu/20.04/amd64/latest/SALTSTACK-GPG-KEY.pub
     Started: 22:57:47.925263
    Duration: 687.385 ms
     Changes:
```

Correct repo uri is (according to https://repo.saltstack.com/#ubuntu):

 https://repo.saltstack.com/py3/ubuntu/20.04/amd64/latest/

**Comment by noelmcloughlin** [comment]
workaround: wget -O - https://repo.saltstack.com/py3/ubuntu/20.04/amd64/latest/SALTSTACK-GPG-KEY.pub | sudo apt-key add -

**Comment by arthurlogilab** [comment]
Same bug for debian. 

Workaround : add the following to your pillars : 

```
salt:
  py_vers: py3
```

Not sure how it would work for py2 deploys

**Comment by major0** [comment]
py2 deploys shouldn't be supported anymore.

**Comment by jeff350** [comment]
This has been resolved with https://github.com/saltstack-formulas/salt-formula/pull/566 by switching to the new Broadcom repos with the generic DEB packages
