### ISSUE TITLE
[BUG] Onedir not supported, therefore Ubuntu 22.04 and others not supported and future Salt versions will break

### ISSUE THREAD

**Issue by bartlaarhoven** [saltstack-formulas/salt-formula#545]
As Salt is moving towards [onedir](https://docs.saltproject.io/salt/install-guide/en/latest/topics/upgrade-to-onedir.html#upgrade-to-onedir) layouts, the repo URLs change as well. Ubuntu 22.04 for example is only available in the onedir format, and the repo URL needs an extra `/salt/` for it to work.

I guess that complete onedir support should be built-in for this formula to work from version 3006 onwards anyway.

**Comment by B1ue-W01f** [comment]
@dafyddj this is the official repo though right? 

Perhaps different if it was the non official repo but just looks bad if Saltstack hosts a Saltstack formula that doesn't work with Saltstack.

**Comment by dafyddj** [comment]
Saltstack as an organisation doesn't exist, and I wouldn't call this formula organization official
