### ISSUE TITLE
[BUG] Packages now live in a different repository

### ISSUE THREAD

**Issue by nigelsim** [saltstack-formulas/salt-formula#565]
As per [this guidance](https://saltproject.io/blog/salt-project-package-repo-migration-and-guidance/), the Salt package repo is now at packages.broadcom.com.

**Comment by sylvainfaivre** [comment]
and the subfolders structure was also changed

**Comment by WraithCadmus** [comment]
They've turned off https://repo.saltproject.io today, so now when you try to run this formula it breaks your DNF.

**Comment by sticky-note** [comment]
Hi, I ended up to propose this https://github.com/saltstack-formulas/salt-formula/pull/566.
Can you confirm it resolves the issue for your case ?
@nigelsim @sylvainfaivre @WraithCadmus

**Comment by WraithCadmus** [comment]
Hello, it all seems to be working as intended now. Part of my confusion was caused by another formula in our infrastructure left over from an upgrade that was managing the repo file, making changes I thought were coming from this formula.
