### ISSUE TITLE
formula fails on CentOS when run from gitfs

### ISSUE THREAD

**Issue by saxonww** [saltstack-formulas/salt-formula#83]
I've recently converted a bunch of formulas I cloned and then referenced via file_roots to local git repos referenced from gitfs_remotes. A couple of formulas now break whenever a dictionary item can't be resolved.

I am using CentOS, and this formula fails because it can't resolve salt.pkrepo.centos. Since this was working fine when pulled from file_roots I am not sure what to say, although wrapping the contents of salt/pkgrepo/init.sls in an if checking for `os_family == 'Debian'` eliminates the problem for me.

**Comment by aboe76** [comment]
could you make a pull request for this change?
