### ISSUE TITLE
Error when running salt.minion

### ISSUE THREAD

**Issue by sanderant** [saltstack-formulas/salt-formula#93]
The following error occurs:
          ID: salt-minion
    Function: file.recurse
        Name: /etc/salt/minion.d
      Result: False
     Comment: #### /etc/salt/minion.d/_defaults.conf ####
              Unable to manage file: Jinja syntax error: no test named 'mapping'
              /var/cache/salt/minion/files/base/salt/formulas.jinja(14):
              ---
              [...]

              {%- macro formulas_git_opt(env, opt) -%}
              {%- set value = salt['pillar.get']('salt_formulas:git_opts:{}:{}'.format(env, opt),
                   salt['pillar.get']('salt_formulas:git_opts:default:{}'.format(opt),
                     defaults[opt])) -%}
              {%- if value is mapping -%}    <======================
              {{ value|yaml }}
              {%- else -%}
              {{ value }}
              {%- endif -%}
              {%- endmacro -%}
              [...]
              ---

Which appears to come from line 14 in  ../salt/formulas.ninja 

Not sure what the right value should be.

**Comment by iggy** [comment]
Mapping is in jinja 2.6+... It may be best to avoid that for formulas for now. If you want to work around it, install jinja from pip to get the latest version.

**Comment by sanderant** [comment]
Thanks that did the trick!
